name: CI

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    # Lint the code
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install
            - run: yarn build:api # Need to build api so that the demo app has a reference to the built code
            - run: yarn lint

    # Test the code
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install
            - run: yarn test
